### ISSUE TITLE
How do you proceed with an experiment with image patch as a qeury?

### ISSUE THREAD

**Issue by ryu0725** [pfnet-research/distilled-feature-fields#11]
I saw your paper interesting interest.
I have a question.
![image](https://user-images.githubusercontent.com/128580671/227892776-a25e2b48-299d-4b9a-8414-c8b0d9a7d8b9.png)

I think the code uses query only as text,
How did you use image patch as query?

**Comment by soskek** [comment]
This repository does not have full features. If you prepare code for using DINO and image patch, it would work!
