### ISSUE TITLE
Problem with import vren

### ISSUE THREAD

**Issue by fangli333** [pfnet-research/distilled-feature-fields#12]
Hi,
my instance verison is CUDA diver 11.7 and cuda version 11.6. But no matter I try to download cuda1.13.1+cu117 or follow your torch and cuda setting. It always show the bug as following. Can you help me solve it?

Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from models.networks import NGP
  File "/home/ubuntu/kevinli/distilled-feature-fields/models/networks.py", line 4, in <module>
    import vren
ImportError: /home/ubuntu/.local/lib/python3.8/site-packages/vren.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEE

**Comment by soskek** [comment]
I'm not familiar with what happens in cuda 11.7 or 11.6.
The README assumes 11.1, and I have checked the env only.
```
# assume cuda 11.1
pip install torch==1.10.2+cu111 torchvision==0.11.3+cu111 --extra-index-url https://download.pytorch.org/whl/cu111 --no-cache-dir
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.2+cu111.html
```

If you changed the version, you might need to modify these commands (cu111 -> cu117). But I don't know if it solves all or not.
