### ISSUE TITLE
Question about installing the pytorch-encoding

### ISSUE THREAD

**Issue by YZsZY** [pfnet-research/distilled-feature-fields#3]
Hello, I tried using my own dataset to test the code, so I follow the instruction to install the pytorch-encoding. But I failed when I installed in the environment with torch1.12.1+cu113 and cuda11.3, the issue in the pytorch-encoding respository said that the pytorch version and the cuda version is too high that it needs to degrade the cuda version back to 10-, but in this case the tinycudann cannot be installed as it requires cuda version 11.0+, so I wonder did you encounter any problems while installing the pytorch-encoding and how did you solve them?

**Comment by soskek** [comment]
Thank you. While I don't have enough time to investigate them carefully, it seems a simple solution to separate environments for preparing feature maps and constructing NeRFs and DFFs. pytorch-encoding would be required only for preparing feature maps. After you've done this, you can remove it.

**Comment by YZsZY** [comment]
> Thank you. While I don't have enough time to investigate them carefully, it seems a simple solution to separate environments for preparing feature maps and constructing NeRFs and DFFs. pytorch-encoding would be required only for preparing feature maps. After you've done this, you can remove it.

Hello, thanks for replying, I have solved this problem as the PyTorch-encoding seems to support cuda11.1 but not support 11.3, just reinstall the torch version with the cuda11.3 can solve this problem

**Comment by cazhang** [comment]
having the same issue here

**Comment by cazhang** [comment]
> 

With cuda 11.3 too, but failed multiple attemps.  Could you share the version of torch with me?

**Comment by cazhang** [comment]
With cuda 11.3 too, but failed multiple attemps. Could you share the version of torch with me? @YZsZY Thanks.
