### ISSUE TITLE
Full code and experiments on other datasets

### ISSUE THREAD

**Issue by zhao-yiqun** [pfnet-research/distilled-feature-fields#4]
Dear authors,

Thanks for your code releasing. I note that your released code do not contains the full experiments of your paper, will your experiments on Replica and LLFF datasets be released (source code and data splits)? Also, the code for render the background and foreground separately shown in the right of your figure 1. in the paper.

Thanks in advance

Regards.

**Comment by soskek** [comment]
Thank you for your kind question!

I'm sorry that I have not planned it now. While I hoped, due to time constraints, I failed to have enough time to make the codebase easy and accessible to everyone.
An excuse is that I don't think that DFFs are difficult implementations or of rigorous forms; it is just a general technique. When people wanna perform some experiments comparing DFFs-related baselines with their proposed method, self-reproduction is good enough or even more fair in their experiments, I guess.

**Comment by zhao-yiqun** [comment]
Thanks for your reply.

I have tried to understand and run your rendering and Decomposing code with the example dataset provided by your project.

I have tried to change the query.yaml to check whether it can be decomposed by different text. What I do is to change the query.yaml from original 
``
query:
``
``
query_type: "text"
``
``
texts: ["apple", "banana", "vegetables", "floor"]
``
to the following
``
query:
``
``
query_type: "text"
``
``
texts: ["apple", "banana"]
``
But the rendering results have no difference, the rendering results is following

Original results:
![rendered_000](https://user-images.githubusercontent.com/91787021/203927025-90578c69-0c96-4520-8576-922c7837586b.png)

Results after change the query.yaml:
![rendered_000](https://user-images.githubusercontent.com/91787021/203927252-21dd6faa-b036-4378-93c4-74f59c1916a3.png)

It seems that there are no difference. Therefore, I wonder if it is the same as your experiments results. If I want to decompose the apple and banana seperately, How should I change the editing configs?

Thanks ,
Regards.

**Comment by soskek** [comment]
Thank you for your understanding.

Hmm. The results were not matched with mine. It seems that decomposition is not performed well even during train.py with CLIPNeRF optimization; that is, it seems not an issue with render.py or query.yaml.
I guess that DFF training is not converged well. Could you try `--num_epochs 8` instead of `--num_epochs 4` when running train.py?

**Comment by zhao-yiqun** [comment]
Sorry but still do not work.

Here is my commands and logs.

python train.py --root_dir sample_dataset --dataset_name colmap --exp_name exp_v1 --downsample 0.25 --num_epochs 8 --batch_size 4096 --scale 4.0 --ray_sampling_strategy same_image --feature_dim 512 --random_bg --feature_directory sample_dataset/rgb_feature_langseg 

GridEncoding: Nmin=16 b=1.38191 F=2 T=2^19 L=16                                                                       
Using 16bit native Automatic Mixed Precision (AMP)                                                                    
GPU available: True, used: True                 
xxxxx
xxxxx(file name print)
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
model.bypass_rgb_net.params torch.Size([9216]) to be optimized
model.xyz_encoder.params torch.Size([12208528]) to be optimized
model.dir_encoder.params torch.Size([0]) to be optimized
model.rgb_net.params torch.Size([8192]) to be optimized
model.feature_encoder.params torch.Size([10615536]) to be optimized
Epoch 7: 100%|█| 1008/1008 [00:53<00:00, 18.70it/s, loss=0.00232, train/rm_s=136.0, train/vr_s=121.0, train/psnr=30.60ckpts/colmap/exp_v1/epoch=7_slim.ckpt 


CLIP-NeRF optimize

python train.py --root_dir sample_dataset --dataset_name colmap --exp_name exp_v1_clip --downsample 0.25 --num_epochs 8 --batch_size 4096 --scale 4.0 --ray_sampling_strategy same_image --feature_dim 512 --random_bg --clipnerf_text rainbow_apple --clipnerf_filter_text apple banana vegetable floor --weight_path ckpts/colmap/exp_v1/epoch=7_slim.ckpt --accumulate_grad_batches 2    
                                
GridEncoding: Nmin=16 b=1.38191 F=2 T=2^19 L=16
['apple', 'banana', 'vegetable', 'floor']
tensor([[1.0000, 0.7898, 0.8494, 0.8001],
        [0.7898, 1.0000, 0.8024, 0.7537],
        [0.8494, 0.8024, 1.0000, 0.8155],
        [0.8001, 0.7537, 0.8155, 1.0000]], device='cuda:0') 
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Loading 49 train images ...
100%|█████████████████████████████████████████████████████████████████████████████████| 49/49 [00:05<00:00,  9.10it/s]Loading 8 test images ...
100%|███████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00,  9.28it/s]LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
model.bypass_rgb_net.params torch.Size([9216]) to be optimized
model.xyz_encoder.params torch.Size([12208528]) to be optimized
model.dir_encoder.params torch.Size([0]) to be optimized
model.rgb_net.params torch.Size([8192]) to be optimized
model.feature_encoder.params torch.Size([10615536]) to be optimized
Epoch 7: 100%|█| 208/208 [00:27<00:00,  7.62it/s, loss=0.796, train/rm_s=120.0, train/vr_s=107.0, train/psnr=27.40, teckpts/colmap/exp_v1_clip/epoch=7_slim.ckpt 


Rendering logs

python render.py --root_dir sample_dataset --dataset_name colmap --downsample 0.25 --scale 4.0 --ray_sampling_strategy same_image --feature_dim 512 --ckpt_path ckpts/colmap/exp_v1_clip/epoch\=7_slim.ckpt --edit_config query.yaml

GridEncoding: Nmin=16 b=1.38191 F=2 T=2^19 L=16
{'query': {'query_type': 'text', 'texts': ['apple', 'banana'], 'positive_ids': [0], 'score_threshold': None}, 'edit': 
{'operations': [{'edit_type': 'extraction'}]}}
/public/home/zhaoyq/anaconda3/envs/bacon/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
100%|███████████████████████████████████████████████████████████████████████████████| 120/120 [00:36<00:00,  3.29it/s]

![rendered_000](https://user-images.githubusercontent.com/91787021/203938186-d4f368fa-7012-4a2f-8f65-01db579782ee.png)

Could you please give me some other advices?

Thanks
Regards

**Comment by zhao-yiqun** [comment]
The Encode Features by Teacher Network

is the same as your README.md

python -u encode_images.py --backbone clip_vitl16_384 --weights demo_e200.ckpt --widehead --no-scaleinv --outdir ../../sample_dataset/rgb_feature_langseg --test-rgb-dir ../../sample_dataset/images

Regards

**Comment by zhao-yiqun** [comment]
Hi

I check the outputs from  LSeg model in rgb_feature_langseg is like this:

![IMG_20220408_142309 png_legend](https://user-images.githubusercontent.com/91787021/203993790-e038c76e-97e1-4800-8d31-45272744ddcb.png)

There is no apple, banana, vegetable in the segmentation results, is this different with you?

**Comment by soskek** [comment]
Thank you for providing the details. They will help a lot to improve this repo!
Note: I'll further investigate after I return from NeurIPS next week.

----

>There is no apple, banana, vegetable in the segmentation results

This behavior itself is correct. The LSeg script just uses prepared label sets, which may not contain apples, etc.

But the result seems largely different from mine. So, something wrong may happen in encode_images.py.
An example of mine is as follows:
![IMG_20220408_142309 png_legend](https://user-images.githubusercontent.com/9245278/204066963-6e7dcd86-5f2c-43f0-9d7d-8de388c0889f.png)
![IMG_20220408_142309 png_vis](https://user-images.githubusercontent.com/9245278/204066964-3c8010e8-ede0-4ae6-b4f0-f84a97198965.png)
![IMG_20220408_142309 png_feature_vis](https://user-images.githubusercontent.com/9245278/204066961-43bf79b2-549b-4e63-a834-24b7c68e7501.png)

**Comment by zhao-yiqun** [comment]
Hi

Thanks for your detail feedback and kindly reply.

With your comments, I check the encode_images.py, and I found the error is that I change the line from this 

`clip_pretrained, _ = clip.load("ViT-B/32", device='cuda', jit=False)`

to 

`clip_pretrained, _ = clip.load("ViT-B/32", device='cpu', jit=False)`

After I change back to cuda, I can get the similar results as yours.
![IMG_20220408_142313 png_vis](https://user-images.githubusercontent.com/91787021/204126697-340f8ef0-76b2-4f55-b16b-737c2f6785d8.png)
![IMG_20220408_142313 png_legend](https://user-images.githubusercontent.com/91787021/204126700-131a92a4-0d62-4b6d-bbd6-64eadad9cee9.png)
![IMG_20220408_142313 png_feature_vis](https://user-images.githubusercontent.com/91787021/204126702-12754e3e-59c7-45a0-b9d3-ee9c9864955d.png)
![IMG_20220408_142313](https://user-images.githubusercontent.com/91787021/204126703-a4b5709c-ce93-42b1-812b-1f17c9b893fa.png)

Now, I used your defalt query.yaml but got the results like this.

![rendered_000](https://user-images.githubusercontent.com/91787021/204126761-29eab76d-1bb2-433a-85d3-9dd868fcfa9f.png)

However in your defalt query.yaml. That is like here:

`query:`

`query_type: "text"`

`texts: ["apple", "banana", "vegetables", "floor"]`

 `positive_ids: [0] # indices of target texts`

 `score_threshold: # empty means None. use argmax.`

`edit:`

 `operations:`

 `- edit_type: "extraction"`

Is this similar as yours? The video in your README is extract by four query words? Since based on my understanding, the decomposed results in your README should be only with only one query words "apple"?

Thanks for your reply.

**Comment by soskek** [comment]
Great! Thank you for your explorations!

This yaml is a little tricky.
>texts: ["apple", "banana", "vegetables", "floor"]
>positive_ids: [0] # indices of target texts

`texts` shows a set of query words. And, `positive_ids` shows which of the queries are "positive" (= target-object) queries. Other queries (here, [1, 2, 3] = ["banana", "vegetables", "floor"]) are used as negative queries.
A coordinate is classified as positive (= apple) if and only if the score of "apple" is larger than any of ["banana", "vegetables", "floor"]. This negative-example-based classification is often effective and easier than score-threshold-based binary classification.

So, for example, if you want to extract banana, set "positive_ids: [1]" or "texts: ["banana", "apple", "vegetables", "floor"] with [0]".

**Comment by zhao-yiqun** [comment]
Thanks for your explanation, now, with your comments, I can extract the banana.

![rendered_000](https://user-images.githubusercontent.com/91787021/204429232-49f26fbe-ad85-4fb3-b995-06833d77ecdb.png)

One more question, If the extract text query is still texts: ["apple", "banana", "vegetables", "floor"], and I want to extract apple and banana at the same time, I found that using "positive_ids: [0, 1]" can not directly achieve this. Does the current implement version only support single-object decomposition?

Regards.

**Comment by soskek** [comment]
Great!!

Oh, really? It might be a bug. I'll check it later.

**Comment by StarsTesla** [comment]
@zhao-yiqun @soskek well, I didn't change the code 
`clip_pretrained, _ = clip.load("ViT-B/32", device='cuda', jit=False)`
but I still got a some wrong label result as you changed:

![1669798046362](https://user-images.githubusercontent.com/45264423/204749781-1687e068-f465-4016-8f1f-ea6d85d82466.png)

![1669798072211](https://user-images.githubusercontent.com/45264423/204749856-45ac85c3-ee06-4559-8e42-ae079e0d6598.png)

**Comment by soskek** [comment]
Hmm, it's strange behavior. While it could be out of my understanding, I'll check it later too. Thank you for reporting.

**Comment by StarsTesla** [comment]
Thansk for that! And I have another question that how should I input a different size of image?

I mean the code in LSeg were:
`base_size = 520` and `crop_size=480`, which are make sense when we input the 1920 x 1080, which means a crop down scale of 4 times, but when I tried to chang it to like 400? because the blender dataset are 800 x 800, I will get a error of tensor shape. I can crop the images, but I cannot get a new transofrm_matrix of blender dataset unless I render again in blender with 1920 x 1080.
And another key is how does the llff dataset process under such situation.

**Comment by StarsTesla** [comment]
@soskek Is the reason about multi-GPU? I run the encoding code on single GPU,  because when I tried to run on 2 or more GPU, the error shows:

`  File "encode_images.py", line 546, in <module>
    test(args)
  File "encode_images.py", line 424, in test
    outputs = evaluator.parallel_forward(image)
  File "/root/code/pycode/DreamNeRF/distilled-feature-fields/lseg_encoder/additional_utils/encoding_models.py", line 64, in parallel_forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/root/anaconda3/envs/LSeg/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/root/anaconda3/envs/LSeg/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 40, in parallel_apply
    assert len(modules) == len(kwargs_tup)
AssertionError`

**Comment by StarsTesla** [comment]
Well，I found this code can be training for CLIP very well, but cannot directly use on DINO feature for training, which will give a lot of noise and a worse feature map（down to 3 d by PCA). In another aspect, when I use the original NeRF model, which can reporduce the DINO results very well, this is very wierd.

I also tried on the code  torch-ngp, which also shows a bad results.

Here is the gt of DINO
<img width="502" alt="1671099737648" src="https://user-images.githubusercontent.com/45264423/207834622-143a06e6-e2c2-4d4b-a68a-bcbaeed290e9.png">

And here is the result of this code for feature
<img width="474" alt="1671099763965" src="https://user-images.githubusercontent.com/45264423/207834835-da394544-ab56-4c1c-942e-a6a02c26a23c.png">

here is the gt of CLIP
<img width="587" alt="1671099880948" src="https://user-images.githubusercontent.com/45264423/207835179-e3a2a6a2-e690-4ef8-aa2a-8f9c27fe5779.png">

and here is the result of CLIP for feature.
<img width="467" alt="1671099921126" src="https://user-images.githubusercontent.com/45264423/207835334-557eefd2-65f4-45a0-bb8b-66a1b4e4f200.png">



I dont know why this is happend, it does not make any sense.

**Comment by soskek** [comment]
@StarsTesla 
Thank you for the great experiments! It is also new to me. The NGP-based DFF implementation is a little different from the vanilla NeRF-based ones. I described some of them here: https://github.com/pfnet-research/distilled-feature-fields/issues/5#issuecomment-1332039782
One of them could harm training DINO-based DFF. Especially, the simplest "non-volumetric rendering" of features could be a risk.
And, DINO features tend to be higher frequency and have more diversity than CLIP features. This may affect PCA appearances. Even if it looks worse and non-cluster in 3 dim, it cloud be nice in high dim, I guess.

I didn't do multi-GPU a lot. So, it is a little difficult to answer right now.

**Comment by StarsTesla** [comment]
Thanks for reply, so I will keeping using the vanilla NeRF-based model for DINO version in my task, and CLIP version for this.
By the way, I found if I change the parameter scales of the "encoding_image.py", would change the results of the problem we mentioned above, but still bad and different from the results of yours, I thought maybe it could be some bug of this? I dont know. 

> @zhao-yiqun @soskek well, I didn't change the code `clip_pretrained, _ = clip.load("ViT-B/32", device='cuda', jit=False)` but I still got a some wrong label result as you changed:
> 
> ![1669798046362](https://user-images.githubusercontent.com/45264423/204749781-1687e068-f465-4016-8f1f-ea6d85d82466.png)
> 
> ![1669798072211](https://user-images.githubusercontent.com/45264423/204749856-45ac85c3-ee06-4559-8e42-ae079e0d6598.png)

**Comment by soskek** [comment]
What does "paramter scales" mean?
This one? https://github.com/pfnet-research/distilled-feature-fields/blob/master/encoders/lseg_encoder/encode_images.py#L353
It is actually important. It could worsen results if bad values are selected.

If bad results with unchanged values, it's a still mystery. I'll retry it later when I find the time.

**Comment by StarsTesla** [comment]
Yeah,if this problem cannot be solved, the "apple" or "banana" cannot be extract.
Here I crop a patch of the feature and compare the mean feature of the patch with the whole image feature learned by dff, I set the sim threshold of 0.99, still got alot of noise feature, instead of only apple.

<img width="474" alt="1671105004070" src="https://user-images.githubusercontent.com/45264423/207852170-ae3f51c3-c3b4-4976-80d2-eb05581ec8bc.png">

And if the DINO version for hash grid NeRF trained well should be like below(hotdog dataset):
<img width="538" alt="0e0f0d35b1eebd8885db42374128358" src="https://user-images.githubusercontent.com/45264423/207852602-ebaaf9e5-26e1-4290-95b6-41cd60c39d70.png">

<img width="635" alt="98d42fba60ddc2c34b5a8ee4e67ba4d" src="https://user-images.githubusercontent.com/45264423/207852735-d4c7be71-8c1e-4d8f-aa7b-5bf8c4116e93.png">

I recall maybe I add direction as input, but it's not reasonable, I also test it on other dataset, gave me a worse results, now the vanilla NeRF still the best choice but slow one.

**Comment by StarsTesla** [comment]
@soskek Hi,there, did you find the solution? cauz this very important to me.

**Comment by soskek** [comment]
Hi. I was waiting for your response after [I asked](https://github.com/pfnet-research/distilled-feature-fields/issues/4#issuecomment-1352932250) and forgot this.

I'll check it.

**Comment by soskek** [comment]
@StarsTesla
Sorry. Could clarify the issues again? What is solved and what is unsolved? I am a little confused when reading your comments now. 
When I retried the installation and run encoding_image.py, the result was nice.
![IMG_20220408_142309 png_legend](https://user-images.githubusercontent.com/9245278/210666407-87842ff2-482b-4952-8a3c-bb00aee23727.png)

**Comment by StarsTesla** [comment]
Thanks for that! I re clone the latest repo and run again, now the error is gone. And here is my instructions as a reference for the other user of the repo.

# Instruction

### 1. clone the repo

```bash
git clone https://github.com/pfnet-research/distilled-feature-fields.git
```

### 2. requiements

```bash
conda list | grep torch

pytorch-lightning         1.6.5                    pypi_0    pypi
torch                     1.10.2+cu111             pypi_0    pypi
torch-encoding            1.2.2b20221130           pypi_0    pypi
torch-scatter             2.1.0                    pypi_0    pypi
torchaudio                0.12.1+cu116             pypi_0    pypi
torchmetrics              0.5.1                    pypi_0    pypi
torchvision               0.11.3+cu111             pypi_0    pypi
```

```
pip list |grep tiny 

tinycudann              1.6

pip list |grep apex

apex                    0.1

pip list |grep clip

clip                    1.0
```

```bash
pip install models/csrc/

Processing ./models/csrc
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: vren
  Building wheel for vren (setup.py) ... done
  Created wheel for vren: filename=vren-2.0-cp38-cp38-linux_x86_64.whl size=2882646 sha256=b50defbed7950923aa2b5598871dd6cffc73bfa7ac9c610674e54758998e4f8f
  Stored in directory: /tmp/pip-ephem-wheel-cache-_qbado2b/wheels/cf/75/81/1987e27761127f61248192967087d371a67255b5329029f020
Successfully built vren
Installing collected packages: vren
Successfully installed vren-2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

```

###  

### 3. download dataset and pretrained model

![7e34201a9836e6f16316b7c1773377c](https://user-images.githubusercontent.com/45264423/210730196-54b69197-eeeb-4a5c-8089-71eedad2b1de.png)






### 4. run the encode_image.py

```bash
export CUDA_VISIBLE_DEVICES=7

python -u encode_images.py --backbone clip_vitl16_384 --weights demo_e200.ckpt --widehead --no-scaleinv --outdir ./sample_dataset/rgb_feature_langseg --test-rgb-dir ./sample_dataset/images
```

```bash
Namespace(acc_bn=False, activation='lrelu', arch_option=0, aux=False, backbone='clip_vitl16_384', base_size=520, batch_size=16, block_depth=0, crop_size=480, cuda=True, data_path=None, dataset='ignore', eval=False, export=None, ignore_index=-1, jobname='default', label_src='default', model='encnet', module='lseg', no_cuda=False, no_val=False, outdir='./sample_dataset/rgb_feature_langseg', resize_max=1.25, scale_inv=False, se_loss=False, se_weight=0.2, seed=1, strict=True, test_batch_size=16, test_rgb_dir='./sample_dataset/images', test_val=False, train_split='train', weights='demo_e200.ckpt', widehead=True, widehead_hr=False, workers=16)
** Use norm [0.5, 0.5, 0.5], [0.5, 0.5, 0.5] as the mean and std **
TORCH_MODEL_ZOO is deprecated, please use env TORCH_HOME instead
test rgb dir ./sample_dataset/images
load ./sample_dataset/images as image directroy for FolderLoader
./sample_dataset/images/./sample_dataset/images/IMG_20220408_142309.png
....
.....
./sample_dataset/images/./sample_dataset/images/IMG_20220408_142522.png
LSegModule(
  (net): LSegNet(
    (clip_pretrained): CLIP(
      (visual): VisionTransformer(
        (conv1): Conv2d(3, 768, kernel_size=(32, 32), stride=(32, 32), bias=False)
..........................................................
..........................................................
..........................................................
      (head1): Conv2d(256, 512, kernel_size=(1, 1), stride=(1, 1))
      (output_conv): Sequential(
        (0): Interpolate()
      )
    )
  )
)
scales [0.75, 1.0, 1.25, 1.75]
test rgb dir ./sample_dataset/images
outdir ./sample_dataset/rgb_feature_langseg
MultiEvalModule: base_size 520, crop_size 480
  0%|                                                                                                                         | 0/57 [00:00<?, ?it/s]150
w, h = 480 360
scales [0.75, 1.0, 1.25, 1.75]
test rgb dir ./sample_dataset/images
outdir ./sample_dataset/rgb_feature_langseg
  0%|                                                                                                                         | 0/57 [00:00<?, ?it/s]Traceback (most recent call last):
  File "encode_images.py", line 546, in <module>
    test(args)
  File "encode_images.py", line 396, in test
    for i, (image, dst) in enumerate(tbar):
  File "/root/anaconda3/envs/LSeg/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/root/anaconda3/envs/LSeg/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/LSeg/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/LSeg/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/LSeg/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/LSeg/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/LSeg/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/LSeg/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/code/git/dff/distilled-feature-fields/encoders/lseg_encoder/data/__init__.py", line 30, in __getitem__
    img = Image.open(self.images[index]).convert('RGB')
  File "/root/anaconda3/envs/LSeg/lib/python3.8/site-packages/PIL/Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './sample_dataset/images/./sample_dataset/images/IMG_20220408_142309.png'
```



### 5. meet bug, change code for right dir

change the file encoder/lseg_encoder/data/init.py line 54 - 56

from:

```python
        imgpath = os.path.join(img_folder, filename)
        img_paths.append(imgpath)
        print(imgpath)
```

to:

```python
        # imgpath = os.path.join(img_folder, filename)
        img_paths.append(filename)
        print(filename)
```

###  6. run again

part of the log 

```bash
start make_pred
done makepred -0.009496927261352539
calculate PCA based on 1st image IMG_20220408_142309.png
PCA(n_components=3, random_state=42)
pca.explained_variance_ratio_ [0.5671965479850769, 0.17677558958530426, 0.11408638954162598]
pca.singular_values_ [64.98482513427734, 36.279083251953125, 29.144866943359375]
-0.28280771255493165 0.6162954008579254
start save
(512, 360, 480)
0.4181673526763916
  2%|█▉                                                                                                               | 1/57 [00:09<08:25,  9.03s/it]torch.Size([3, 1440, 1920]) image.shape -
resize torch.Size([3, 1440, 1920]) to (360, 480)
torch.Size([3, 360, 480])
torch.Size([3, 360, 480]) image.shape
start pred
done pred -2.511078119277954
start make_pred
done makepred -0.00882267951965332
start save
(512, 360, 480)
0.2798190116882324
  4%|███▉                                                                                                             | 2/57 [00:15<07:01,  7.67s/it]torch.Size([3, 1440, 1920]) image.shape -
resize torch.Size([3, 1440, 1920]) to (360, 480)
torch.Size([3, 360, 480])
  4%|███▉       
```
![1672905475209](https://user-images.githubusercontent.com/45264423/210730079-b683cdd1-7e49-4606-bb92-3a58dc320a93.png)

**Comment by soskek** [comment]
I'm glad that the problem was solved!
I also modified `encoders/lseg_encoder/data/__init__.py` as you suggested, thanks a lot!
