### ISSUE TITLE
feature field size in DINO

### ISSUE THREAD

**Issue by dsshim0125** [pfnet-research/distilled-feature-fields#6]
Hi,

Thank you for your great work!

I've noticed that the feature map of teacher network (DINO) is downsampled by 4 with the kernel size of 8 and the stride of 4 as mentioned in the paper.

Does the feature map from DINO upsampled (e.g. bilinear, bicubic) to be the same size as the input image?

Thank you!

**Comment by soskek** [comment]
Thank you for your comment.

https://github.com/pfnet-research/distilled-feature-fields/blob/bfb0cc9bb4c486a4365365ee01ecee8debd6870f/datasets/base.py#L67
In this implementation, I used [torch.nn.functional.grid_sample](https://pytorch.org/docs/stable/generated/torch.nn.functional.grid_sample.html) for obtaining a feature vector for supervising a ray of the distilled feature field.
```
feats = torch.nn.functional.grid_sample(feature_map, sampler, mode='bilinear', align_corners=True)
```
`sampler` is [-1, 1]-based coordinate. So, it is versatile for any `feature_map.shape`. You do not have to exactly resize the feature map in advance.

**Comment by soskek** [comment]
I believe it got solved.
