### ISSUE TITLE
Bad results on LLFF datasets

### ISSUE THREAD

**Issue by yuehaowang** [pfnet-research/distilled-feature-fields#7]
Hi, thanks for sharing this excellent work!

I'm trying the optimization-based editing on the LLFF datasets. I've managed to reproduce some results of the 'flower' scene. However, when I trained a model on the 'orchids' scene, I found the reconstruction results are bad. This is the command I used for training:

```
python train.py --root_dir /path/to/nerf_llff_data/orchids --exp_name orchids --downsample 0.25 --batch_size 1024 --scale 2. --dataset_name colmap --feature_directory /path/to/features/orchids --feature_dim 512 --ray_sampling_strategy same_image
```

I also tested the same command (except feature-related options and --ray_sampling_strategy) with the original [ngp_pl code](https://github.com/kwea123/ngp_pl). And it works.  Below is the result comparison between this code repo and ngp_pl.

| DFFs (This repo)  |  ngp_pl  |
|---|---|
|![image](https://user-images.githubusercontent.com/6317569/211921726-443b7ff3-c215-4499-81a5-32f2f0f546b7.png)   |  ![image](https://user-images.githubusercontent.com/6317569/211921945-5b286f85-f802-483b-b8ec-5407bf87e969.png) |

Besides the 'orchids' scene, I also failed in some other LLFF format data.
I would greatly appreciate it if someone could shed some light on this problem.

**Comment by soskek** [comment]
I don't know. I guess that LLFF data (forward-facing) requires NDC conversion to work well, and it is not implemented in this repo.

**Comment by soskek** [comment]
- Is NDC conversion implemented in the original ngp_pl? (many commits ahead of kwea123:master)
- If ray_sampling_strategy is `all_images`, success?

**Comment by yuehaowang** [comment]
Thank you very much for your prompt response.

I carefully looked into the differences between the settings I ran ngp_pl and DFFs. I found this issue is caused by my use of the wrong image folder. Since I ran the feature encoder on the downsampled images, I mistakenly loaded the 'images_4' folder when training DFFs. After I fixed this, it works!

Thanks again for your patience and help.

**Comment by soskek** [comment]
Great!!
