### ISSUE TITLE
!problems with training!

### ISSUE THREAD

**Issue by PatrickDDj** [pfnet-research/distilled-feature-fields#8]
I have done all preparations for training,including apex, tinycuda. My torch version is 1.13.1+cu116.
Once I trained the first DFF, I came across such err as below:
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from models.networks import NGP
  File "/home/DFF/models/networks.py", line 3, in <module>
    import tinycudann as tcnn
  File "/opt/conda/lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/opt/conda/lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann/modules.py", line 50, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /opt/conda/lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann_bindings/_86_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE

**Comment by soskek** [comment]
It seems that you failed to install tinycudann itself.
Did the tinycudann work by itself?
If it fails, it would be an issue with your installation of tinycudann. I cannot solve it in this thread. Please see the tinycudann repository.

And, note that [DFF README](https://github.com/pfnet-research/distilled-feature-fields#example) uses 1.10.2+cu111. I didn't check if later versions work.

**Comment by PatrickDDj** [comment]
Ok，I created a new conda environment and solved this problem.

**Comment by fangli333** [comment]
> inycudann_bindings/_86_C

Can you show how you solve this problem? My instance is CUDA 11.7. Can you show your torch, cuda and CUDA verison? Thank you.
