### ISSUE TITLE
Feature map for the example desired!

### ISSUE THREAD

**Issue by PatrickDDj** [pfnet-research/distilled-feature-fields#9]
Can you provide the feature map for the example? It can be frustrating to generate this myself.

**Comment by soskek** [comment]
Unfortunately, it is also tough to host the large files...
I uploaded it but will delete within a week.
https://drive.google.com/file/d/1PJElSKcwZTzzvhUFglLd4k9RYaDg_1Nw/view?usp=share_link

**Comment by soskek** [comment]
@PatrickDDj  Can I delete it?

**Comment by soskek** [comment]
@PatrickDDj Can I delete it?

**Comment by soskek** [comment]
@PatrickDDj Can I delete it?

**Comment by soskek** [comment]
Thank you...

**Comment by R-QinQ** [comment]
> Unfortunately, it is also tough to host the large files... I uploaded it but will delete within a week. https://drive.google.com/file/d/1PJElSKcwZTzzvhUFglLd4k9RYaDg_1Nw/view?usp=share_link

I need it，too,  can you open it again?

**Comment by soskek** [comment]
@R-QinQ 

OK!
https://drive.google.com/file/d/12gRux0BVx73sax2Yc6GOycGZznfHKQMF/view
Please download it within a few days!

**Comment by R-QinQ** [comment]
> @R-QinQ
> 
> OK! https://drive.google.com/file/d/12gRux0BVx73sax2Yc6GOycGZznfHKQMF/view Please download it within a few days!

Thank you very much！！！
